package p000X;

/* renamed from: X.0jS  reason: invalid class name and case insensitive filesystem */
public enum C13910jS {
    UploadAvatarViaFbAttempt("try_facebook_auth", "upload_avatar_via_fb_attempt"),
    LoginUsernamePrefilled("login_username_prefilled", "field_prefilled"),
    FbClashDialog("fb_clash_dialog"),
    FbClashLoginTapped("fb_clash_log_in_tapped"),
    RemoveTapped("remove_tapped"),
    RemoveConfirmed("remove_confirmed"),
    RemoveCancel("remove_cancel"),
    OneTapFailed("sso_failed", "one_tap_failed"),
    OneTapLoginAccountClicked("one_tap_login_account_clicked"),
    InvalidOneTapLinkDialogShow("show_invalid_one_tap_link_dialog"),
    InvalidOneTapLinkDialogAction("invalid_one_tap_link_dialog"),
    LandingCreated("landing_created"),
    SwitchToSignUp("switch_to_sign_up"),
    SwitchToLogin("switch_to_log_in"),
    ClickOnContactPoint("click_on_contact_point", "choose_contact_point"),
    PasswordRecoveryTapped("pw_recovery_tapped"),
    IgLocalExposure("ig_local_exposure"),
    IgD3LocalExposure("initial_app_launch_experiment_exposure"),
    SwitchToPhone("switch_to_phone", "switch_flow"),
    SwitchToEmail("switch_to_email", "switch_flow"),
    ResendConfirmation("resend_confirmation", "resend_code"),
    GuessedCountryCode("guessed_country_code"),
    CountryCodeChange("country_code_change"),
    SendPhoneIdRequest("send_phone_id_request"),
    PhoneIdResponseReceived("phone_id_response_received"),
    PrefillPhoneNumber("prefill_phone_number", "field_prefilled"),
    EmailFieldPrefilled("email_field_prefilled", "field_prefilled"),
    AttemptReadEmailForPrefill("attempt_read_email_for_prefill"),
    FoundEmailForPrefill("found_email_for_prefill"),
    EmailPrefillAccepted("email_prefill_accepted"),
    PhonePrefillAccepted("phone_prefill_accepted"),
    SimCardState("sim_card_state"),
    ContactPointPermissionPrepromptNotShow("contact_point_permission_preprompt_not_show"),
    ContactPointPermissionPrepromptShow("contact_point_permission_preprompt_show", "permission_preprompt_reg"),
    ContactPointPermissionPrepromptAllow("contact_point_permission_preprompt_allow", "permission_preprompt_reg"),
    ContactPointPermissionPrepromptDeny("contact_point_permission_preprompt_deny", "permission_preprompt_reg"),
    ContactPointPermissionPrepromptResults("contact_point_permission_preprompt_results", "permission_preprompt_reg"),
    ChooseFacebook("choose_facebook", "choose_fb"),
    TryFacebookAuth("try_facebook_auth", "fb_sso_attempt"),
    FacebookAuthSucceeded("facebook_auth_succeeded", "fb_sso_success"),
    CancelFacebookAuth("cancel_facebook_auth", "fb_sso_cancel"),
    FacebookAuthError("facebook_auth_error", "fb_sso_error"),
    TryFacebookSso("try_facebook_sso", "fb_sso_attempt"),
    CanRecoverPassword("can_recover_password"),
    RecoverPassword("recover_password"),
    FacebookSsoError("facebook_sso_error", "fb_sso_error"),
    RegisterWithFacebook("register_with_facebook"),
    RegisterWithEmail("register_with_email", "fb_clash_new_account_tapped"),
    ShowContinueAsUserNotFound("show_continue_as_user_not_found", "continue_as_server_call"),
    ShowContinueAsFailed("show_continue_as_failed", "continue_as_server_call"),
    ShowContinueAsSucceeded("show_continue_as_succeeded", "continue_as_server_call"),
    BailOnPhoneId("bail_on_phone_id", "continue_as_server_call"),
    ShowContinueAsFinished("show_continue_as_finished"),
    IgHandleShown("ig_handle_shown", "continue_as_loaded"),
    ContinueAsShown("continue_as_shown", "continue_as_loaded"),
    FirstPartyTokenAcquired("first_party_token_acquired"),
    LanguageSelectorClicked("language_selector_clicked", "language_select_tapped"),
    LanguageChanged("language_changed", "language_switched"),
    ChooseBusinessSignUp("choose_business_sign_up", "choose_business"),
    RegisterFullNameFocused("register_full_name_focused", "text_field_focus"),
    RegisterPasswordFocused("register_password_focused", "text_field_focus"),
    RegisterUsernameFocused("register_username_focused", "text_field_focus"),
    ValidPassword("valid_password"),
    RegFlowExtrasCached("reg_flow_extras_cached"),
    RegisterAvatarClicked("register_avatar_clicked", "upload_avatar_tapped"),
    SetProfilePhotoDialogCanceled("set_profile_photo_dialog_canceled", "upload_avatar_tapped"),
    RegisterAccountRequestSubmitted("register_account_request_submitted", "next_tapped"),
    RegisterAccountFailed("register_account_failed", "next_blocked"),
    RegisterAccountErrorResolutionAttempt("register_account_retry", "next_blocked"),
    RegisterWithCIOption("register_with_ci_option"),
    RegisterCountryCodeSelected("register_country_code_selected"),
    GetGoogleTokenAttempt("get_google_token_attempt"),
    GetGoogleTokenSuccess("get_google_token_success"),
    GetGoogleTokenFail("get_google_token_fail"),
    PassGoogleToken("pass_google_token"),
    ConfirmEmailAfterReg("confirm_email_after_reg"),
    GetGoogleAccountAttempt("get_google_account_attempt"),
    GetGoogleAccountSuccess("get_google_account_success"),
    GetGoogleAccountFailure("get_google_account_failure"),
    LookUpWithGoogleIdTokens("look_up_with_google_id_tokens"),
    RegScreenLoaded("step_view_loaded", "step_loaded"),
    RegBackPressed("back_button_tapped", "back_tapped"),
    RegNextPressed("next_button_tapped", "next_tapped"),
    RegSkipPressed("skip_button_tapped"),
    RegFieldInteracted("reg_field_interacted"),
    RegSkipConfirmed("skip_confirmed"),
    RegSuggestionPrefilled("suggestion_prefilled", "field_prefilled"),
    RegNextBlocked("next_blocked"),
    RegFlowAborted("registration_flow_aborted"),
    ConnectAfterSkip("connect_after_skip"),
    ConnectWithFriends("connect_with_friends"),
    UserListImpression("user_list_impression"),
    UserListProfileTapped("user_list_profile_tapped"),
    UserListFollowButtonTapped("user_list_follow_button_tapped"),
    FollowAllButtonTapped("follow_all_button_tapped"),
    FollowAllAttempted("follow_all_attempted"),
    ContactsLoadSuccess("contacts_load_success"),
    FriendsLoadSuccess("friends_load_success"),
    FollowAllDialogImpression("follow_all_dialog_impression"),
    FollowAllDialogCancelled("follow_all_dialog_cancelled"),
    FollowAllDialogConfirmed("follow_all_dialog_confirmed"),
    ConfirmSkipDialogShow("confirm_skip_dialog_show"),
    ConfirmSkipDialogCancelTapped("confirm_skip_dialog_cancel_tapped"),
    ConfirmSkipDialogSkipTapped("confirm_skip_dialog_skip_tapped"),
    RequestFailedDialogShow("request_failed_dialog_show"),
    RequestFailedDialogSkipTapped("request_failed_dialog_skip_tapped"),
    RequestFailedDialogTryAgainTapped("request_failed_dialog_try_again_tapped"),
    SmsPermissionAllowed("sms_permission_allowed"),
    SmsPermissionDenied("sms_permission_denied"),
    BackgroundConfirmSmsParsed("background_confirm_sms_parsed"),
    BackgroundConfirmSuccess("background_confirm_success"),
    PhoneNumberAutoConfirmed("phone_number_auto_confirmed"),
    ManualConfirmSuccessWhileBackgroundConfirmEnabled("manual_confirm_success_while_bgc_enabled"),
    BackgroundConfirmFailed("background_confirm_failed"),
    StepViewBackgrounded("step_view_backgrounded"),
    NoPrototypeSent("no_prototype_sent"),
    UsernameSuggestionPrototypesReceived("username_suggestion_prototypes_received"),
    UsernameSuggestionPrototypeUsed("usename_suggestion_prototype_used"),
    UsernameSuggestionPrototypeAccepted("username_suggestion_prototype_accepted"),
    UsernameSuggestionPrototypeRejected("username_suggestion_prototype_rejected"),
    AccessDialogLoaded("step_view_loaded", "access_dialog"),
    AccessDialogSwitchToSignUpLoaded("switch_to_signup_dialog_loaded", "access_dialog"),
    AccessDialogSwitchToSignUpNegativeButtonTapped("switch_to_signup_negative_tapped", "access_negative_tapped"),
    AccessDialogSwitchToSignUpPositiveButtonTapped("switch_to_signup_positive_tapped", "access_positive_tapped"),
    RegRecoveryTapped("recovery_tapped", "access_recovery_tapped"),
    RegClickSingleAccountLogIn("click_single_account_log_in"),
    RegClickMultipleAccountLogIn("click_multiple_account_log_in"),
    RegRetryTapped("retry_tapped", "access_retry_tapped"),
    RegLogInTapped("login_tapped", "access_login_tapped"),
    RegPasswordPhoneCodeSentDialogPresented("received_code_dialog_impression"),
    RegPasswordResetLinkSentDialogPresented("received_link_dialog_impression"),
    RegPasswordResetLinkDialogOkClicked("click_okay_on_link"),
    PhoneAutologinDialogLoaded("phone_autologin_dialog_loaded"),
    PhoneAutologinDialogLogInTapped("phone_autologin_dialog_log_in_tapped"),
    PhoneAutologinDialogCreateAccountTapped("phone_autologin_dialog_create_account_tapped"),
    CheckpointScreenLoaded("step_view_loaded"),
    CheckpointThisWasMeTapped("this_was_me"),
    CheckpointThisWasntMeTapped("this_wasnt_me"),
    CheckpointNextBlocked("next_blocked"),
    CheckpointNextTapped("next_tapped"),
    CheckpointResendBlocked("resend_blocked"),
    CheckpointResendTapped("resend_tapped"),
    CheckpointDismiss("dismiss"),
    TryFetchAdditionalPhoneNumber("try_fetch_additional_phone_number"),
    AdditionalPhoneNumberRequestSuccess("additional_phone_number_request_success"),
    AdditionalPhoneNumberRequestFail("additional_phone_number_request_fail"),
    AdditionalPhoneNumberPresent("additional_phone_number_present"),
    AdditionalPhoneNumberParseFail("additional_phone_number_parse_fail"),
    SaveAdditionalPhoneNumberSuccess("save_additional_phone_success"),
    SaveAdditionalPhoneNumberFail("save_additional_phone_fail"),
    AddEmailSuccess("add_email_success"),
    AddEmailFail("add_email_fail"),
    AddEmailEmailSourceInfo("nux_add_email_source_info"),
    FetchEmailInNux("fetch_email_in_nux"),
    FetchEmailInNuxResult("AgeVerificationFragment.java"),
    TermsOfServiceLinkClicked("terms_of_service_link_clicked"),
    LogInUsernameFocus("log_in_username_focus", "text_field_focus"),
    LogInPasswordFocus("log_in_password_focus", "text_field_focus"),
    LogInAttempt("log_in_attempt", "next_tapped"),
    ForceLogoutLoginHelperAttempt("force_logout_login_helper_attempt"),
    ForgotFacebook("forgot_facebook"),
    ForgotNeedMoreHelp("forgot_need_more_help"),
    PrefillLookupIdentifier("prefill_lookup_identifier"),
    RecoveryEmail("recovery_email"),
    RecoverySms("recovery_sms"),
    RecoveryWhatsApp("recovery_whatsapp"),
    RecoveryFacebook("recovery_facebook"),
    NoAccessTapped("no_access_tapped"),
    PasswordResetAttempt("password_reset_attempt"),
    PasswordResetFieldOneFocus("password_reset_field_pwd_focus"),
    PasswordResetFieldTwoFocus("password_reset_field_pwd_conf_focus"),
    PasswordResetSuccess("password_reset_success"),
    PasswordResetFailed("password_reset_fail"),
    Pushable("pushable"),
    Pushed("pushed"),
    PushDismissed("push_dismissed"),
    PushTapped("push_tapped"),
    FacebookSsoSuccess("facebook_sso_success", "fb_sso_success"),
    RegisterAccountCreated("register_account_created", "reg_success"),
    LogIn("log_in", "log_in_success"),
    LogInSso("log_in_sso", "log_in_one_tap"),
    LoggedIn("ig_log_in"),
    ContactsUpsellViewed("nux_contacts_upsell_viewed", "ig_android_nux"),
    ContactsUpsellAccepted("nux_contacts_upsell_accepted", "ig_android_nux"),
    ContactsUpsellDeclined("contacts_upsell_declined", "ig_android_nux"),
    ContactsUpsellAutoDeclined("nux_contacts_upsell_automatically_declined", "ig_android_nux"),
    CpntactsImportOptIn("contacts_import_opt_in", "ig_android_nux"),
    ContactListEmptyStateConnectContactsButtonTapped("contact_list_empty_state_connect_contacts_button_tapped", "ig_android_nux"),
    ContactListEmptyStatePrivacyPolicyLinkTapped("contact_list_empty_state_privacy_policy_link_tapped", "ig_android_nux"),
    ContactListEmptyStatePrivacyPolicyDialogLearnMoreTapped("contact_list_empty_state_privacy_policy_dialog_learn_more_tapped", "ig_android_nux"),
    FacebookFirstPartyAuth("facebook_first_party_auth"),
    DynamicOnboardingStep("ig_dynamic_onboarding_step"),
    DynamicOnboardingReceivedStepsFromServer("ig_dynamic_onboarding_updated_steps_from_server"),
    NuxStarted("ig_nux_started"),
    NuxFinished("id_nux_finished"),
    GoogleSmartLockAccountDialogDisplayed("ig_android_smart_lock_account_dialog_displayed"),
    GoogleSmartLockDialogAccountSelected("ig_android_smart_lock_dialog_account_selected"),
    GoogleSmartLockAccountDialogDismissed("ig_android_smart_lock_account_dialog_dismissed"),
    GoogleSmartLockNoAccountSelected("ig_android_smart_lock_dialog_no_account_selected"),
    GoogleSmartLockLoginAttempt("ig_android_smart_lock_login_attempt"),
    GoogleSmartLockError("ig_android_smart_lock_error"),
    GoogleSmartLockSavePassword("ig_android_smart_lock_save_password"),
    GoogleSmartLockPrefill("ig_android_smartlock_prefill"),
    GoogleSmartLockAutoSignIn("ig_android_smart_lock_auto_sign_in"),
    SmsRetrieverStarted("ig_android_sms_retriever_started"),
    SmsRetrieverReceivedSms("ig_android_sms_retriever_received_sms"),
    SmsRetrieverError("ig_android_sms_retriever_error"),
    TwoFacLoginStepViewLoaded("step_view_loaded"),
    TwoFacLoginBackButtonTapped("back_button_tapped"),
    TwoFacLoginNextButtonTapped("next_button_tapped"),
    TwoFacLoginNextBlocked("next_blocked"),
    TwoFacLoginResendSMSTapped("two_fac_resend_sms_tapped"),
    TwoFacLoginFailed("two_fac_login_failed"),
    SACMainAccountCandidatesImpression("main_account_candidates_impression"),
    SACLearnMoreLabelTapped("learn_more_label_tapped"),
    SACMainAccountSelected("main_account_selected"),
    SACInfoButtonTapped("info_button_tapped"),
    SACNextConfirmed("next_confirmed"),
    SACUsernameCheckSuccess("username_check_success"),
    SACUsernameCheckFail("username_check_fail"),
    SACSignUpWithCPButtonTapped("sign_up_with_cp_button_tapped"),
    SACUsernameSuggestionTapped("username_suggestion_tapped"),
    SACHalfSheetCreateNewAccountTapped("half_sheet_create_new_account_tapped"),
    SACHalfSheetLogIntoExistingAccountTapped("half_sheet_log_into_existing_account_tapped"),
    SACNUXFollowFromLoggedInAccountsSkipTapped("follow_from_logged_in_accounts_skip_tapped"),
    SACNUXFollowFromLoggedInAccountsDoneTapped("follow_from_logged_in_accounts_done_tapped"),
    SACNUXFollowFromLoggedInAccountsUserRowTapped("follow_from_logged_in_accounts_user_row_tapped"),
    SACNUXFollowFromLoggedInAccountsFollowButtonTapped("follow_from_logged_in_accounts_follow_button_tapped"),
    SACNUXFollowFromLoggedInAccountsUnfollowButtonTapped("follow_from_logged_in_accounts_unfollow_button_tapped"),
    AddBirthDayMoreInfoTapped("birthday_more_info_tapped"),
    BirthdayInfoLearnMoreTapped("birthday_info_learn_more_tapped"),
    AskForParentalApprovalTapped("ask_for_parental_approval_tapped"),
    ParentEmailSendTapped("parent_email_send_tapped"),
    ParentEmailInvalid("parent_email_invalid"),
    AddAgeInsteadTapped("birthday_add_age_instead_tapped"),
    AddBirthdayInsteadTapped("add_birthday_instead_tapped"),
    SharedEmailAutocompleteAccountDialogShown("shared_email_autocomplete_account_dialog_shown"),
    SharedEmailAutocompleteAccountDialogLogin("shared_email_autocomplete_account_dialog_login"),
    SharedEmailAutocompleteAccountDialogReg("shared_email_autocomplete_account_dialog_reg"),
    SharedEmailEmailTakenDialogShown("shared_email_email_taken_dialog_shown"),
    SharedEmailEmailTakenDialogLogin("shared_email_email_taken_dialog_login"),
    SharedEmailEmailTakenDialogReg("shared_email_email_taken_dialog_reg"),
    PrivateAccountTapped("private_account_tapped"),
    PublicAccountTapped("public_account_tapped"),
    SuggestedUserFollowButtonTapped("suggested_user_follow_button_tapped"),
    InterestFollowsUserScrolled("interest_follows_on_scroll"),
    InterestFollowsDoneButtonDisabled("interest_follows_done_disabled"),
    InterestFollowsDoneButtonEnabled("interest_follows_done_enabled"),
    InterestFollowsFollowButtonTapped("interest_follows_follow_button_tapped"),
    InterestFollowsUnFollowButtonTapped("interest_follows_unfollow_button_tapped"),
    InterestFollowsSeeMoreButtonTapped("interest_follows_see_more_button_tapped");
    
    public final String A00;
    public final String A01;

    public static String A00() {
        return C13920jT.A00("log_in").A05();
    }

    public final C55182aC A01(C06590Pq r4) {
        return new C55182aC(r4, this.A01, this.A00);
    }

    /* access modifiers changed from: public */
    C13910jS(String str) {
        this.A01 = str;
        this.A00 = str;
    }

    /* access modifiers changed from: public */
    C13910jS(String str, String str2) {
        this.A01 = str;
        this.A00 = str2;
    }
}
