package p000X;

import com.instagram.quickpromotion.intf.QuickPromotionSurface;
import com.instagram.quickpromotion.intf.Trigger;
import java.util.EnumSet;

/* renamed from: X.1k8  reason: invalid class name and case insensitive filesystem */
public enum C37731k8 {
    PROFILE_MEGAPHONE_SURFACE(QuickPromotionSurface.MEGAPHONE, EnumSet.of(Trigger.PROFILE_HEADER, Trigger.LOGGED_IN_USER_ID_LOADED)),
    PROFILE_TOOLTIP_SURFACE(QuickPromotionSurface.TOOLTIP, EnumSet.of(Trigger.PROFILE_TOOLTIP)),
    PROFILE_INTERSTITIAL_SURFACE(QuickPromotionSurface.INTERSTITIAL, EnumSet.of(Trigger.PROFILE_PROMPT)),
    PROFILE_OTHER_MEGAPHONE_SURFACE(QuickPromotionSurface.MEGAPHONE, EnumSet.of(Trigger.PROFILE_OTHER_HEADER)),
    PROFILE_OTHER_TOOLTIP_SURFACE(QuickPromotionSurface.TOOLTIP, EnumSet.of(Trigger.PROFILE_OTHER_TOOLTIP, Trigger.PROFILE_OTHER_CHECKOUT_TOOLTIP)),
    PROFILE_OTHER_INTERSTITIAL_SURFACE(QuickPromotionSurface.INTERSTITIAL, EnumSet.of(Trigger.PROFILE_OTHER_PROMPT)),
    FEED_MEGAPHONE_SURFACE(QuickPromotionSurface.MEGAPHONE, EnumSet.of(Trigger.FEED_HEADER)),
    FEED_TOOLTIP_SURFACE(QuickPromotionSurface.TOOLTIP, EnumSet.of(Trigger.FEED_TOOLTIP, Trigger.NAVIGATION_TOOLTIP)),
    FEED_INTERSTITIAL_SURFACE(QuickPromotionSurface.INTERSTITIAL, EnumSet.of(Trigger.FEED_PROMPT, Trigger.SHOPPING_STORY_POSTED)),
    INBOX_HEADER_SURFACE(QuickPromotionSurface.MEGAPHONE, EnumSet.of(Trigger.INBOX_HEADER)),
    INBOX_INTERSTITIAL_SURFACE(QuickPromotionSurface.INTERSTITIAL, EnumSet.of(Trigger.INBOX_PROMPT)),
    INBOX_SEARCH_HEADER_SURFACE(QuickPromotionSurface.MEGAPHONE, EnumSet.of(Trigger.INBOX_SEARCH_HEADER)),
    INBOX_TOOLTIP_SURFACE(QuickPromotionSurface.TOOLTIP, EnumSet.of(Trigger.INBOX_TOOLTIP, Trigger.INBOX_FILTER_TOOLTIP)),
    DIRECT_APP_INBOX_HEADER_SURFACE(QuickPromotionSurface.MEGAPHONE, EnumSet.of(Trigger.DIRECT_APP_INBOX_HEADER)),
    IGTV_VIEWER_INTERSTITIAL_SURFACE(QuickPromotionSurface.INTERSTITIAL, EnumSet.of(Trigger.IGTV_VIEWER_PROMPT)),
    LIVE_COMPOSE_TOOLTIP_SURFACE(QuickPromotionSurface.TOOLTIP, EnumSet.of(Trigger.LIVE_COMPOSE_TOOLTIP)),
    DIRECT_APP_INBOX_INTERSTITIAL_SURFACE(QuickPromotionSurface.INTERSTITIAL, EnumSet.of(Trigger.DIRECT_APP_INBOX_PROMPT)),
    FEED_SHARING_HEADER_SURFACE(QuickPromotionSurface.MEGAPHONE, EnumSet.of(Trigger.FEED_SHARING_HEADER)),
    FEED_SHARING_INTERSTITIAL_SURFACE(QuickPromotionSurface.INTERSTITIAL, EnumSet.of(Trigger.FEED_SHARING_PROMPT)),
    ACCOUNT_SETTING_TOOLTIP_SURFACE(QuickPromotionSurface.TOOLTIP, EnumSet.of(Trigger.ACCOUNT_SETTING_TOOLTIP)),
    ACTIVITY_FEED_HEADER_SURFACE(QuickPromotionSurface.MEGAPHONE, EnumSet.of(Trigger.ACTIVITY_FEED_HEADER)),
    ACTIVITY_FEED_INTERSTITIAL_SURFACE(QuickPromotionSurface.INTERSTITIAL, EnumSet.of(Trigger.ACTIVITY_FEED_PROMPT)),
    BRANDED_CONTENT_AND_SHOPPING_ACTIVITY_FEED_HEADER_SURFACE(r15, EnumSet.of(Trigger.BRANDED_CONTENT_AND_SHOPPING_ACTIVITY_FEED_HEADER)),
    EXPLORE_HEADER_SURFACE(r15, EnumSet.of(Trigger.EXPLORE_HEADER)),
    EXPLORE_INTERSTITIAL_SURFACE(QuickPromotionSurface.INTERSTITIAL, EnumSet.of(Trigger.EXPLORE_PROMPT)),
    HASHTAG_FEED_TOOLTIP_SURFACE(r15, EnumSet.of(Trigger.HASHTAG_FEED_TOOLTIP)),
    SHOPPING_HOME_TOOLTIP_SURFACE(r15, EnumSet.of(Trigger.SHOPPING_SAVE_DIRECTORY_TOOLTIP)),
    SHOPPING_PRODUCT_DETAILS_TOOLTIP_SURFACE(r15, EnumSet.of(Trigger.SHOPPING_PRODUCT_DETAILS_LOADED)),
    SAVE_HOME_TOOLTIP_SURFACE(r15, EnumSet.of(Trigger.SAVE_HOME_LOADED)),
    LOCATION_PAGE_INFO_TOOLTIP_SURFACE(r15, EnumSet.of(Trigger.LOCATION_PAGE_INFO_LOADED)),
    SHARE_POST_TOOLTIP_SURFACE(r15, EnumSet.of(Trigger.SHARE_POST_LOADED, Trigger.SHARE_TO_FB_SWITCHED_OFF)),
    SHARE_POST_INTERSTITIAL_SURFACE(r15, EnumSet.of(Trigger.SHARE_POST_LOADED, Trigger.SHARE_TO_FB_SWITCHED_ON)),
    SURVEY_INTERSTITIAL_SURFACE(r15, EnumSet.of(Trigger.SURVEY)),
    ACCOUNT_INSIGHTS_HEADER_SURFACE(QuickPromotionSurface.MEGAPHONE, EnumSet.of(Trigger.ACCOUNT_INSIGHTS_HEADER)),
    STORY_VIEW_TOOLTIP_SURFACE(QuickPromotionSurface.TOOLTIP, EnumSet.of(Trigger.STORY_VIEW_FUNDRAISER_STICKER_TOOLTIP)),
    QUICK_PROMOTION_TEST_MEGAPHONE_SURFACE(QuickPromotionSurface.MEGAPHONE, EnumSet.of(Trigger.QUICK_PROMOTION_TEST)),
    EDIT_PROFILE_TOOLTIP_SURFACE(QuickPromotionSurface.TOOLTIP, EnumSet.of(Trigger.EDIT_PROFILE)),
    CLOSE_FRIENDS_HEADER_SURFACE(QuickPromotionSurface.MEGAPHONE, EnumSet.of(Trigger.CLOSE_FRIENDS_HEADER)),
    DIRECT_IN_THREAD_MESSAGE_FOOTER(QuickPromotionSurface.MESSAGE_FOOTER, EnumSet.of(Trigger.IN_THREAD_MESSAGE_FOOTER));
    
    public final QuickPromotionSurface A00;
    public final EnumSet A01;

    /* access modifiers changed from: public */
    C37731k8(QuickPromotionSurface quickPromotionSurface, EnumSet enumSet) {
        this.A00 = quickPromotionSurface;
        this.A01 = enumSet;
    }
}
