package p000X;

import com.facebook.common.dextricks.DexStore;
import com.facebook.react.uimanager.BaseViewManager;
import com.facebook.video.videoprotocol.config.PlaybackSettings;
import java.util.HashSet;
import java.util.Set;
import org.webrtc.CameraVideoCapturer;

/* renamed from: X.1ni  reason: invalid class name and case insensitive filesystem */
public final class C39881ni {
    public int A00;
    public int A01;
    public int A02;
    public int A03;
    public int A04;
    public int A05;
    public int A06;
    public int A07;
    public int A08;
    public int A09;
    public int A0A = 3;
    public int A0B;
    public int A0C;
    public int A0D;
    public int A0E;
    public int A0F;
    public int A0G;
    public int A0H;
    public int A0I;
    public long A0J;
    public long A0K;
    public C40111o6 A0L;
    public C40111o6 A0M;
    public C40111o6 A0N;
    public C40111o6 A0O;
    public C40111o6 A0P;
    public C40111o6 A0Q;
    public C40001nu A0R;
    public C40071o2 A0S;
    public C39901nk A0T;
    public C39961nq A0U;
    public C40011nv A0V;
    public C40051o0 A0W;
    public C39981ns A0X;
    public C39911nl A0Y;
    public C39911nl A0Z;
    public C40091o4 A0a;
    public C40031nx A0b;
    public PlaybackSettings A0c;
    public String A0d;
    public String A0e = null;
    public Set A0f;
    public Set A0g;
    public Set A0h;
    public Set A0i;
    public Set A0j;
    public boolean A0k;
    public boolean A0l;
    public boolean A0m;
    public boolean A0n;
    public boolean A0o;
    public boolean A0p;
    public boolean A0q;
    public boolean A0r;
    public boolean A0s;
    public boolean A0t = false;
    public boolean A0u;
    public boolean A0v;
    public boolean A0w;
    public boolean A0x;
    public boolean A0y;
    public boolean A0z;
    public boolean A10;
    public boolean A11;
    public boolean A12;
    public boolean A13 = true;
    public boolean A14;
    public boolean A15;
    public boolean A16;
    public boolean A17;
    public boolean A18;
    public boolean A19;
    public boolean A1A;
    public boolean A1B;
    public boolean A1C;
    public boolean A1D;
    public boolean A1E;
    public boolean A1F;
    public boolean A1G;
    public boolean A1H;
    public boolean A1I;
    public boolean A1J;
    public boolean A1K;
    public boolean A1L;
    public boolean A1M;
    public boolean A1N;
    public boolean A1O;
    public boolean A1P;
    public boolean A1Q;
    public boolean A1R;
    public boolean A1S;
    public boolean A1T;
    public boolean A1U;
    public boolean A1V;
    public boolean A1W;
    public boolean A1X;
    public boolean A1Y;
    public boolean A1Z;
    public boolean A1a;
    public boolean A1b;
    public boolean A1c;
    public boolean A1d;
    public boolean A1e;
    public boolean A1f;
    public boolean A1g;
    public boolean A1h = true;
    public boolean A1i;
    public boolean A1j = true;
    public boolean A1k;
    public boolean A1l;
    public boolean A1m;
    public boolean A1n;
    public boolean A1o;
    public boolean A1p;
    public boolean A1q;
    public boolean A1r;
    public boolean A1s;

    public C39881ni() {
        C39891nj r6 = new C39891nj();
        int i = r6.A02;
        long j = r6.A04;
        long j2 = j;
        int i2 = i;
        this.A0T = new C39901nk((String) null, (String) null, false, i2, 0, j2, r6.A03, false, false, 0, r6.A01, r6.A00);
        this.A0r = false;
        this.A1X = true;
        this.A0H = 1000;
        this.A14 = false;
        this.A0Y = new C39911nl(500, CameraVideoCapturer.CameraStatistics.CAMERA_OBSERVER_PERIOD_MS);
        this.A0Z = new C39911nl(0, 0);
        new C39951np();
        this.A0U = new C39961nq(0, 0, BaseViewManager.CAMERA_DISTANCE_NORMALIZATION_MULTIPLIER, 0, 0, 0, BaseViewManager.CAMERA_DISTANCE_NORMALIZATION_MULTIPLIER, 0);
        new C39971nr();
        this.A0X = new C39981ns();
        this.A1Q = false;
        this.A1U = false;
        this.A0n = false;
        this.A1T = false;
        this.A0R = new C40001nu(new C39991nt());
        this.A0V = new C40011nv();
        new C40021nw();
        this.A0b = new C40031nx();
        new C40041ny();
        this.A0c = new PlaybackSettings();
        this.A0W = C40051o0.A00;
        this.A0S = new C40071o2(new C40061o1());
        new C40081o3();
        this.A0a = new C40091o4();
        this.A01 = 12323;
        this.A00 = 14151;
        this.A16 = false;
        this.A1P = false;
        this.A02 = 100;
        C40101o5 r10 = new C40101o5();
        r10.A01 = 100000;
        r10.A05 = 1000;
        r10.A04 = 500;
        r10.A03 = 250;
        this.A0L = new C40111o6(r10);
        C40101o5 r5 = new C40101o5();
        r5.A01 = CameraVideoCapturer.CameraStatistics.CAMERA_OBSERVER_PERIOD_MS;
        r5.A05 = 150000;
        r5.A04 = 550000;
        r5.A03 = 2000000;
        this.A0Q = new C40111o6(r5);
        this.A17 = false;
        this.A0B = 2;
        this.A0q = false;
        this.A1c = false;
        this.A0p = false;
        this.A0v = false;
        this.A0w = false;
        this.A1Z = false;
        this.A0o = false;
        this.A11 = false;
        this.A10 = false;
        this.A07 = 2;
        this.A08 = 4;
        this.A1m = false;
        this.A1C = false;
        this.A0s = false;
        this.A1B = false;
        this.A1r = false;
        this.A1k = false;
        this.A1K = false;
        this.A1J = false;
        this.A1b = false;
        this.A1p = false;
        this.A1l = false;
        this.A1H = false;
        this.A1e = false;
        this.A19 = false;
        this.A0I = 3;
        this.A0D = 100;
        this.A0E = 1;
        this.A0C = 600000;
        this.A1W = false;
        this.A1N = false;
        this.A1o = false;
        this.A1D = false;
        this.A09 = CameraVideoCapturer.CameraStatistics.CAMERA_FREEZE_REPORT_TIMOUT_MS;
        this.A1O = true;
        this.A1Y = false;
        this.A1s = false;
        this.A06 = DexStore.LOAD_RESULT_DEX2OAT_TRY_PERIODIC_PGO_COMP;
        this.A05 = DexStore.LOAD_RESULT_PGO_ATTEMPTED;
        this.A04 = 0;
        this.A03 = 12000;
        this.A0f = new HashSet();
        this.A12 = false;
        this.A0z = false;
        this.A0u = false;
        this.A0J = 0;
        this.A1L = false;
        this.A1M = false;
        this.A1a = false;
        this.A1V = false;
        this.A1g = false;
        this.A0G = 500000;
        this.A0F = 256000;
        this.A18 = false;
        this.A0x = false;
        this.A1I = false;
        this.A0h = new HashSet();
        this.A0g = new HashSet();
        this.A0j = new HashSet();
        this.A0i = new HashSet();
        this.A0m = false;
        this.A0l = false;
        this.A0k = false;
    }
}
