package p000X;

import java.io.Serializable;

/* renamed from: X.1nu  reason: invalid class name and case insensitive filesystem */
public final class C40001nu implements Serializable {
    public final float A00;
    public final float A01;
    public final float A02;
    public final float A03;
    public final float A04;
    public final float A05;
    public final float A06;
    public final float A07;
    public final float A08;
    public final float A09;
    public final float A0A;
    public final float A0B;
    public final float A0C;
    public final float A0D;
    public final float A0E;
    public final float A0F;
    public final int A0G;
    public final int A0H;
    public final int A0I;
    public final int A0J;
    public final int A0K;
    public final int A0L;
    public final int A0M;
    public final int A0N;
    public final int A0O;
    public final int A0P;
    public final int A0Q;
    public final int A0R;
    public final int A0S;
    public final int A0T;
    public final int A0U;
    public final int A0V;
    public final int A0W;
    public final int A0X;
    public final int A0Y;
    public final int A0Z;
    public final int A0a;
    public final int A0b;
    public final int A0c;
    public final int A0d;
    public final int A0e;
    public final int A0f;
    public final int A0g;
    public final int A0h;
    public final int A0i;
    public final String A0j;
    public final String A0k;
    public final boolean A0l;
    public final boolean A0m;
    public final boolean A0n;
    public final boolean A0o;
    public final boolean A0p;
    public final boolean A0q;
    public final boolean A0r;
    public final boolean A0s;

    public C40001nu(C39991nt r2) {
        this.A0b = r2.A0b;
        this.A0c = r2.A0c;
        this.A0a = r2.A0a;
        this.A0Z = r2.A0Z;
        this.A0Y = r2.A0Y;
        this.A0X = r2.A0X;
        this.A0V = r2.A0V;
        this.A0G = r2.A0G;
        this.A0e = r2.A0e;
        this.A0f = r2.A0f;
        this.A00 = r2.A00;
        this.A0I = r2.A0I;
        this.A0i = r2.A0i;
        this.A0l = r2.A0l;
        this.A0F = r2.A0F;
        this.A0m = r2.A0m;
        this.A0q = r2.A0q;
        this.A0B = r2.A0B;
        this.A0C = r2.A0C;
        this.A0D = r2.A0D;
        this.A0E = r2.A0E;
        this.A0n = r2.A0n;
        this.A0A = r2.A0A;
        this.A0s = r2.A0s;
        this.A0r = r2.A0r;
        this.A0d = r2.A0d;
        this.A0h = r2.A0h;
        this.A0j = r2.A0j;
        this.A0k = r2.A0k;
        this.A01 = r2.A01;
        this.A02 = r2.A02;
        this.A0W = r2.A0W;
        this.A0g = r2.A0g;
        this.A0Q = r2.A0Q;
        this.A0R = r2.A0R;
        this.A0P = r2.A0P;
        this.A0L = r2.A0L;
        this.A0N = r2.A0N;
        this.A07 = r2.A07;
        this.A0J = r2.A0J;
        this.A0K = r2.A0K;
        this.A0S = r2.A0S;
        this.A0T = r2.A0T;
        this.A03 = r2.A03;
        this.A04 = r2.A04;
        this.A0M = r2.A0M;
        this.A0p = r2.A0p;
        this.A08 = r2.A08;
        this.A09 = r2.A09;
        this.A0H = r2.A0H;
        this.A0o = r2.A0o;
        this.A05 = r2.A05;
        this.A06 = r2.A06;
        this.A0O = r2.A0O;
        this.A0U = r2.A0U;
    }
}
