package p000X;

import com.facebook.react.uimanager.BaseViewManager;
import java.util.Arrays;

/* renamed from: X.20a  reason: invalid class name and case insensitive filesystem */
public final class C465820a {
    public float A00 = 1.0f;
    public float A01 = BaseViewManager.CAMERA_DISTANCE_NORMALIZATION_MULTIPLIER;
    public float A02 = BaseViewManager.CAMERA_DISTANCE_NORMALIZATION_MULTIPLIER;
    public float A03 = -1.0f;
    public float A04 = 1.0f;
    public float A05 = 0.5f;
    public float A06 = BaseViewManager.CAMERA_DISTANCE_NORMALIZATION_MULTIPLIER;
    public float A07 = BaseViewManager.CAMERA_DISTANCE_NORMALIZATION_MULTIPLIER;
    public float A08 = BaseViewManager.CAMERA_DISTANCE_NORMALIZATION_MULTIPLIER;
    public float A09 = BaseViewManager.CAMERA_DISTANCE_NORMALIZATION_MULTIPLIER;
    public float A0A = 1.0f;
    public float A0B = 1.0f;
    public float A0C = Float.NaN;
    public float A0D = Float.NaN;
    public float A0E = BaseViewManager.CAMERA_DISTANCE_NORMALIZATION_MULTIPLIER;
    public float A0F = BaseViewManager.CAMERA_DISTANCE_NORMALIZATION_MULTIPLIER;
    public float A0G = BaseViewManager.CAMERA_DISTANCE_NORMALIZATION_MULTIPLIER;
    public float A0H = 0.5f;
    public float A0I = BaseViewManager.CAMERA_DISTANCE_NORMALIZATION_MULTIPLIER;
    public float A0J = 1.0f;
    public int A0K = -1;
    public int A0L = -1;
    public int A0M = -1;
    public int A0N = -1;
    public int A0O = -1;
    public int A0P = 0;
    public int A0Q = -1;
    public int A0R = -1;
    public int A0S = -1;
    public int A0T = -1;
    public int A0U = -1;
    public int A0V = -1;
    public int A0W = -1;
    public int A0X = -1;
    public int A0Y = -1;
    public int A0Z = -1;
    public int A0a = -1;
    public int A0b = -1;
    public int A0c = -1;
    public int A0d = 0;
    public int A0e = -1;
    public int A0f = -1;
    public int A0g = 0;
    public int A0h = -1;
    public int A0i = -1;
    public int A0j = -1;
    public int A0k = -1;
    public int A0l;
    public int A0m = -1;
    public int A0n;
    public int A0o;
    public int A0p = -1;
    public int A0q = -1;
    public int A0r = -1;
    public int A0s = -1;
    public int A0t = -1;
    public int A0u = -1;
    public int A0v = -1;
    public int A0w = -1;
    public int A0x = -1;
    public int A0y = -1;
    public int A0z = 0;
    public int A10 = 0;
    public int A11 = 0;
    public int A12 = -1;
    public int A13 = -1;
    public String A14 = null;
    public String A15;
    public boolean A16 = false;
    public boolean A17 = false;
    public boolean A18 = false;
    public boolean A19 = false;
    public boolean A1A = false;
    public int[] A1B;

    public final void A00(C31691Zj r2) {
        r2.A0T = this.A0i;
        r2.A0U = this.A0j;
        r2.A0k = this.A0r;
        r2.A0l = this.A0s;
        r2.A0p = this.A0y;
        r2.A0o = this.A0x;
        r2.A0D = this.A0N;
        r2.A0C = this.A0M;
        r2.A0B = this.A0K;
        r2.A0m = this.A0u;
        r2.A0n = this.A0v;
        r2.A0J = this.A0U;
        r2.A0I = this.A0T;
        r2.leftMargin = this.A0h;
        r2.rightMargin = this.A0q;
        r2.topMargin = this.A0w;
        r2.bottomMargin = this.A0L;
        r2.A0O = this.A0Z;
        r2.A0L = this.A0W;
        r2.A03 = this.A05;
        r2.A09 = this.A0H;
        r2.A0E = this.A0O;
        r2.A0F = this.A0P;
        r2.A01 = this.A01;
        r2.A0s = this.A14;
        r2.A0G = this.A0Q;
        r2.A0H = this.A0R;
        r2.A0A = this.A0I;
        r2.A04 = this.A06;
        r2.A0q = this.A0z;
        r2.A0S = this.A0g;
        r2.A0u = this.A18;
        r2.A0t = this.A17;
        r2.A0W = this.A11;
        r2.A0V = this.A0d;
        r2.A0Y = this.A12;
        r2.A0X = this.A0e;
        r2.A0a = this.A13;
        r2.A0Z = this.A0f;
        r2.A06 = this.A0J;
        r2.A05 = this.A04;
        r2.A0b = this.A0p;
        r2.A02 = this.A03;
        r2.A0Q = this.A0b;
        r2.A0R = this.A0c;
        r2.width = this.A0o;
        r2.height = this.A0l;
        r2.setMarginStart(this.A0t);
        r2.setMarginEnd(this.A0S);
        r2.A00();
    }

    public final /* bridge */ /* synthetic */ Object clone() {
        C465820a r2 = new C465820a();
        r2.A1A = this.A1A;
        r2.A0o = this.A0o;
        r2.A0l = this.A0l;
        r2.A0b = this.A0b;
        r2.A0c = this.A0c;
        r2.A03 = this.A03;
        r2.A0i = this.A0i;
        r2.A0j = this.A0j;
        r2.A0r = this.A0r;
        r2.A0s = this.A0s;
        r2.A0y = this.A0y;
        r2.A0x = this.A0x;
        r2.A0N = this.A0N;
        r2.A0M = this.A0M;
        r2.A0K = this.A0K;
        r2.A0u = this.A0u;
        r2.A0v = this.A0v;
        r2.A0U = this.A0U;
        r2.A0T = this.A0T;
        r2.A05 = this.A05;
        r2.A0H = this.A0H;
        r2.A14 = this.A14;
        r2.A0Q = this.A0Q;
        r2.A0R = this.A0R;
        r2.A05 = this.A05;
        r2.A05 = this.A05;
        r2.A05 = this.A05;
        r2.A05 = this.A05;
        r2.A05 = this.A05;
        r2.A0p = this.A0p;
        r2.A0h = this.A0h;
        r2.A0q = this.A0q;
        r2.A0w = this.A0w;
        r2.A0L = this.A0L;
        r2.A0S = this.A0S;
        r2.A0t = this.A0t;
        r2.A10 = this.A10;
        r2.A0X = this.A0X;
        r2.A0a = this.A0a;
        r2.A0Y = this.A0Y;
        r2.A0V = this.A0V;
        r2.A0W = this.A0W;
        r2.A0Z = this.A0Z;
        r2.A0I = this.A0I;
        r2.A06 = this.A06;
        r2.A0g = this.A0g;
        r2.A0z = this.A0z;
        r2.A00 = this.A00;
        r2.A16 = this.A16;
        r2.A02 = this.A02;
        r2.A07 = this.A07;
        r2.A08 = this.A08;
        r2.A09 = this.A09;
        r2.A0A = this.A0A;
        r2.A0B = this.A0B;
        r2.A0C = this.A0C;
        r2.A0D = this.A0D;
        r2.A0E = this.A0E;
        r2.A0F = this.A0F;
        r2.A0G = this.A0G;
        r2.A18 = this.A18;
        r2.A17 = this.A17;
        r2.A11 = this.A11;
        r2.A0d = this.A0d;
        r2.A12 = this.A12;
        r2.A0e = this.A0e;
        r2.A13 = this.A13;
        r2.A0f = this.A0f;
        r2.A0J = this.A0J;
        r2.A04 = this.A04;
        r2.A0k = this.A0k;
        r2.A0m = this.A0m;
        int[] iArr = this.A1B;
        if (iArr != null) {
            r2.A1B = Arrays.copyOf(iArr, iArr.length);
        }
        r2.A0O = this.A0O;
        r2.A0P = this.A0P;
        r2.A01 = this.A01;
        r2.A19 = this.A19;
        return r2;
    }
}
