package p000X;

/* renamed from: X.CHF */
public enum CHF {
    UNSET_OR_UNRECOGNIZED_ENUM_VALUE,
    CREDIT_CARD_CATEGORY_DEBIT,
    CREDIT_CARD_CATEGORY_CREDIT,
    CREDIT_CARD_CATEGORY_CHARGE,
    CREDIT_CARD_CATEGORY_PREPAID,
    CREDIT_CARD_CATEGORY_DEFERRED_DEBIT,
    CREDIT_CARD_CATEGORY_PREPAID_AND_DEBIT,
    CREDIT_CARD_CATEGORY_COMBO,
    CREDIT_CARD_CATEGORY_UNKNOWN;

    public final String toString() {
        return name();
    }
}
