package com.facebook.video.heroplayer.ipc;

import android.os.Parcel;
import android.os.Parcelable;
import com.facebook.redex.PCreatorEBaseShape0S0000000_I0;
import p000X.AnonymousClass000;
import p000X.C39751nS;
import p000X.C41961rG;
import p000X.C43711ux;

public class HttpTransferEndEvent extends C41961rG implements Parcelable {
    public static final Parcelable.Creator CREATOR = new PCreatorEBaseShape0S0000000_I0(10);
    public final int A00;
    public final int A01;
    public final int A02;
    public final int A03;
    public final int A04;
    public final int A05;
    public final int A06;
    public final int A07;
    public final int A08;
    public final long A09;
    public final long A0A;
    public final long A0B;
    public final long A0C;
    public final long A0D;
    public final long A0E;
    public final long A0F;
    public final long A0G;
    public final long A0H;
    public final long A0I;
    public final long A0J;
    public final long A0K;
    public final long A0L;
    public final long A0M;
    public final long A0N;
    public final long A0O;
    public final long A0P;
    public final long A0Q;
    public final long A0R;
    public final long A0S;
    public final long A0T;
    public final C43711ux A0U;
    public final String A0V;
    public final String A0W;
    public final String A0X;
    public final String A0Y;
    public final String A0Z;
    public final String A0a;
    public final String A0b;
    public final String A0c;
    public final String A0d;
    public final String A0e;
    public final String A0f;
    public final String A0g;
    public final String A0h;
    public final String A0i;
    public final String A0j;
    public final String A0k;
    public final String A0l;
    public final boolean A0m;
    public final boolean A0n;
    public final boolean A0o;
    public final boolean A0p;
    public final boolean A0q;
    public final boolean A0r;
    public final boolean A0s;
    public final boolean A0t;
    public final boolean A0u;
    public final boolean A0v;
    public final boolean A0w;
    public final boolean A0x;
    public final boolean A0y;
    public final boolean A0z;

    public final int describeContents() {
        return 0;
    }

    public final String toString() {
        return AnonymousClass000.A0B("timeMs=", this.A0Q) + AnonymousClass000.A0E(", videoId=", this.A0l) + AnonymousClass000.A0B(", playerId=", this.A0J) + AnonymousClass000.A0E(", url=", this.A0j) + AnonymousClass000.A0E(", exception=", this.A0b) + AnonymousClass000.A0S(", isPrefetch=", this.A0v) + AnonymousClass000.A0E(", prefetchSource=", this.A0f) + AnonymousClass000.A05(", readBytes=", this.A05) + AnonymousClass000.A0B(", queueDuration=", this.A0K) + AnonymousClass000.A0B(", startDuration=", this.A0S) + AnonymousClass000.A0B(", endDuration=", this.A0R) + AnonymousClass000.A05(", seqNum=", this.A08) + AnonymousClass000.A0E(", cacheType=", this.A0U.A01) + AnonymousClass000.A0S(", isFirstPlay=", this.A0r) + AnonymousClass000.A0E(", playOrigin=", this.A0d) + AnonymousClass000.A0E(", debugInfo=", this.A0Z) + AnonymousClass000.A0B(", startingByteOffset=", this.A0P) + AnonymousClass000.A0B(", requestedLength=", this.A0L) + AnonymousClass000.A05(", streamType=", this.A07) + AnonymousClass000.A0B(", segmentStart=", this.A0M) + AnonymousClass000.A05(", segmentDuration=", this.A06) + AnonymousClass000.A0E(", dataSourceFactory=", this.A0Y) + AnonymousClass000.A0E(", qualityLabel=", this.A0g) + AnonymousClass000.A0E(", connQual=", this.A0W) + AnonymousClass000.A05(", networkPriority=", this.A04) + AnonymousClass000.A05(", bufferedDurationMs=", this.A00) + AnonymousClass000.A0B(", startVideoBandwidth=", this.A0N) + AnonymousClass000.A0B(", startVideoTTFB=", this.A0O) + AnonymousClass000.A0B(", ligerVideoProcessBandwidth=", this.A0E) + AnonymousClass000.A0B(", ligerMainProcessBandwidth=", this.A0D) + AnonymousClass000.A0E(", videoBandwidthEstimateStr=", this.A0k) + AnonymousClass000.A0B(", upstreamTTFB=", this.A0T) + AnonymousClass000.A0E(", tigonSessionId=", this.A0h) + AnonymousClass000.A0E(", tigonTransactionId=", this.A0i) + AnonymousClass000.A0B(", manifestFirstSegmentStartTs=", this.A0F) + AnonymousClass000.A0B(", manifestLastSegmentEndTs=", this.A0G) + AnonymousClass000.A0B(", manifestNumSegments=", this.A0H) + AnonymousClass000.A0S(", cancelled=", this.A0m) + AnonymousClass000.A05(", bufferedDurationMsAtDataSpecCreation=", this.A01) + AnonymousClass000.A0B(", dataSpecCreationTimeMs=", this.A0C) + AnonymousClass000.A0E(", playSubOrigin=", this.A0e) + AnonymousClass000.A0S(", isFBMS=", this.A0p) + AnonymousClass000.A0S(", isFbPredictiveDASH=", this.A0q) + AnonymousClass000.A0S(", isSkipAheadChunk=", this.A0w) + AnonymousClass000.A0S(", inRewoundState=", this.A0n) + AnonymousClass000.A0S(", isManifestDynamic=", this.A0t) + AnonymousClass000.A0S(", isChunkedTransfer=", this.A0o) + AnonymousClass000.A0S(", isPredictedURL=", this.A0u) + AnonymousClass000.A0B(", numSegmentsToEndOfManifest= ", this.A0I) + AnonymousClass000.A0E(", edgeHit= ", this.A0a) + AnonymousClass000.A0E(", originHit= ", this.A0c) + AnonymousClass000.A0E(", codec= ", this.A0V) + AnonymousClass000.A0B(", cdnResponseTime= ", this.A0A) + AnonymousClass000.A0E(", contentType= ", this.A0X) + AnonymousClass000.A05(", latestSegmentId= ", this.A03) + AnonymousClass000.A0B(", confidenceBasedBitrateEstimate=", this.A0B) + AnonymousClass000.A05(", confidencePctForBitrateEstimate=", this.A02);
    }

    public final void writeToParcel(Parcel parcel, int i) {
        parcel.writeLong(this.A0Q);
        parcel.writeString(this.A0l);
        parcel.writeLong(this.A0J);
        parcel.writeString(this.A0j);
        parcel.writeString(this.A0b);
        parcel.writeByte(this.A0v ? (byte) 1 : 0);
        parcel.writeString(this.A0f);
        parcel.writeInt(this.A05);
        parcel.writeLong(this.A0K);
        parcel.writeLong(this.A0S);
        parcel.writeLong(this.A0R);
        parcel.writeInt(this.A08);
        parcel.writeValue(this.A0U);
        parcel.writeByte(this.A0r ? (byte) 1 : 0);
        parcel.writeString(this.A0d);
        parcel.writeString(this.A0e);
        parcel.writeString(this.A0Z);
        parcel.writeLong(this.A0P);
        parcel.writeLong(this.A0L);
        parcel.writeInt(this.A07);
        parcel.writeLong(this.A0M);
        parcel.writeInt(this.A06);
        parcel.writeString(this.A0Y);
        parcel.writeString(this.A0g);
        parcel.writeString(this.A0W);
        parcel.writeInt(this.A04);
        parcel.writeLong(this.A09);
        parcel.writeByte(this.A0s ? (byte) 1 : 0);
        parcel.writeInt(this.A00);
        parcel.writeLong(this.A0N);
        parcel.writeLong(this.A0O);
        parcel.writeByte(this.A0x ? (byte) 1 : 0);
        parcel.writeByte(this.A0y ? (byte) 1 : 0);
        parcel.writeByte(this.A0z ? (byte) 1 : 0);
        parcel.writeLong(this.A0E);
        parcel.writeLong(this.A0D);
        parcel.writeString(this.A0k);
        parcel.writeLong(this.A0T);
        parcel.writeString(this.A0h);
        parcel.writeString(this.A0i);
        parcel.writeLong(this.A0F);
        parcel.writeLong(this.A0G);
        parcel.writeLong(this.A0H);
        parcel.writeByte(this.A0m ? (byte) 1 : 0);
        parcel.writeInt(this.A01);
        parcel.writeLong(this.A0C);
        parcel.writeByte(this.A0p ? (byte) 1 : 0);
        parcel.writeByte(this.A0q ? (byte) 1 : 0);
        parcel.writeByte(this.A0w ? (byte) 1 : 0);
        parcel.writeByte(this.A0n ? (byte) 1 : 0);
        parcel.writeByte(this.A0t ? (byte) 1 : 0);
        parcel.writeByte(this.A0o ? (byte) 1 : 0);
        parcel.writeByte(this.A0u ? (byte) 1 : 0);
        parcel.writeLong(this.A0I);
        parcel.writeString(this.A0a);
        parcel.writeString(this.A0c);
        parcel.writeString(this.A0V);
        parcel.writeLong(this.A0A);
        parcel.writeString(this.A0X);
        parcel.writeInt(this.A03);
        parcel.writeLong(this.A0B);
        parcel.writeInt(this.A02);
    }

    public HttpTransferEndEvent(long j, String str, long j2, String str2, String str3, boolean z, String str4, int i, long j3, long j4, long j5, int i2, C43711ux r20, boolean z2, String str5, String str6, long j6, long j7, int i3, long j8, int i4, String str7, String str8, String str9, int i5, long j9, boolean z3, int i6, long j10, long j11, boolean z4, boolean z5, boolean z6, long j12, long j13, String str10, long j14, String str11, String str12, long j15, long j16, long j17, boolean z7, int i7, long j18, String str13, boolean z8, boolean z9, boolean z10, boolean z11, boolean z12, boolean z13, boolean z14, long j19, String str14, String str15, String str16, long j20, String str17, int i8, long j21, int i9) {
        super(C39751nS.HTTP_TRANSFER_END);
        this.A0Q = j;
        this.A0l = str;
        this.A0J = j2;
        this.A0j = str2;
        this.A0b = str3;
        this.A0v = z;
        this.A0f = str4;
        this.A05 = i;
        this.A0K = j3;
        this.A0S = j4;
        this.A0R = j5;
        this.A08 = i2;
        this.A0U = r20;
        this.A0r = z2;
        this.A0d = str5;
        this.A0e = str13;
        this.A0Z = str6;
        this.A0P = j6;
        this.A0L = j7;
        this.A07 = i3;
        this.A0M = j8;
        this.A06 = i4;
        this.A0Y = str7;
        this.A0g = str8;
        this.A0W = str9;
        this.A04 = i5;
        this.A09 = j9;
        this.A0s = z3;
        this.A00 = i6;
        this.A0N = j10;
        this.A0O = j11;
        this.A0x = z4;
        this.A0y = z5;
        this.A0z = z6;
        this.A0E = j12;
        this.A0D = j13;
        this.A0k = str10;
        this.A0T = j14;
        this.A0h = str11;
        this.A0i = str12;
        this.A0F = j15;
        this.A0G = j16;
        this.A0H = j17;
        this.A0m = z7;
        this.A01 = i7;
        this.A0C = j18;
        this.A0p = z8;
        this.A0q = z9;
        this.A0w = z10;
        this.A0n = z11;
        this.A0t = z12;
        this.A0o = z13;
        this.A0u = z14;
        this.A0I = j19;
        this.A0a = str14;
        this.A0c = str15;
        this.A0V = str16;
        this.A0A = j20;
        this.A0X = str17;
        this.A03 = i8;
        this.A0B = j21;
        this.A02 = i9;
    }

    public HttpTransferEndEvent(Parcel parcel) {
        super(C39751nS.HTTP_TRANSFER_END);
        this.A0Q = parcel.readLong();
        this.A0l = parcel.readString();
        this.A0J = parcel.readLong();
        this.A0j = parcel.readString();
        this.A0b = parcel.readString();
        boolean z = false;
        this.A0v = parcel.readByte() == 1;
        this.A0f = parcel.readString();
        this.A05 = parcel.readInt();
        this.A0K = parcel.readLong();
        this.A0S = parcel.readLong();
        this.A0R = parcel.readLong();
        this.A08 = parcel.readInt();
        this.A0U = (C43711ux) parcel.readValue(C43711ux.class.getClassLoader());
        this.A0r = parcel.readByte() == 1;
        this.A0d = parcel.readString();
        this.A0e = parcel.readString();
        this.A0Z = parcel.readString();
        this.A0P = parcel.readLong();
        this.A0L = parcel.readLong();
        this.A07 = parcel.readInt();
        this.A0M = parcel.readLong();
        this.A06 = parcel.readInt();
        this.A0Y = parcel.readString();
        this.A0g = parcel.readString();
        this.A0W = parcel.readString();
        this.A04 = parcel.readInt();
        this.A09 = parcel.readLong();
        this.A0s = parcel.readByte() == 1;
        this.A00 = parcel.readInt();
        this.A0N = parcel.readLong();
        this.A0O = parcel.readLong();
        this.A0x = parcel.readByte() == 1;
        this.A0y = parcel.readByte() == 1;
        this.A0z = parcel.readByte() == 1;
        this.A0E = parcel.readLong();
        this.A0D = parcel.readLong();
        this.A0k = parcel.readString();
        this.A0T = parcel.readLong();
        this.A0h = parcel.readString();
        this.A0i = parcel.readString();
        this.A0F = parcel.readLong();
        this.A0G = parcel.readLong();
        this.A0H = parcel.readLong();
        this.A0m = parcel.readByte() == 1;
        this.A01 = parcel.readInt();
        this.A0C = parcel.readLong();
        this.A0p = parcel.readByte() == 1;
        this.A0q = parcel.readByte() == 1;
        this.A0w = parcel.readByte() == 1;
        this.A0n = parcel.readByte() == 1;
        this.A0t = parcel.readByte() == 1;
        this.A0o = parcel.readByte() == 1;
        this.A0u = parcel.readByte() == 1 ? true : z;
        this.A0I = parcel.readLong();
        this.A0a = parcel.readString();
        this.A0c = parcel.readString();
        this.A0V = parcel.readString();
        this.A0A = parcel.readLong();
        this.A0X = parcel.readString();
        this.A03 = parcel.readInt();
        this.A0B = parcel.readLong();
        this.A02 = parcel.readInt();
    }
}
